[features]
seeds = false
[programs.localnet]
sol_transfer2 = "FhbFwFVKe1NwzSxPSatgwACiRHpaeaccAA7rmqBpTc8R"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
